#!/usr/bin/env python3
"""
table_4_track_fragmentation.py — Reproduce Table 4 (SG track fragmentation
relative to AV2 tracks) from the paper.

Reads precomputed fragmentation rows for GT scenario tracks from
summaries/fragmentation.json (generated by precompute_summaries.py).

Run from the repo root:
    python replicate_data/table_4_track_fragmentation.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT    = Path(__file__).resolve().parent.parent
SUMMARIES_DIR = Path(__file__).resolve().parent


def main() -> None:
    frag_path = SUMMARIES_DIR / "fragmentation.json"
    if not frag_path.exists():
        print(f"fragmentation.json not found at {frag_path}")
        sys.exit(1)

    with open(frag_path) as f:
        gt_rows = json.load(f)

    if not gt_rows:
        print("No GT scenario tracks found in fragmentation.json")
        sys.exit(1)

    n          = len(gt_rows)
    frags_mean = sum(r["num_sg_fragments"]           for r in gt_rows) / n
    frag_rate  = sum(r["is_fragmented"]              for r in gt_rows) / n * 100
    dom_cov    = sum(r["dominant_fragment_coverage"] for r in gt_rows) / n * 100

    col = 20
    header = (f"{'Total # Tracks':>{col}}  {'Fragments / Track':>{col}}  "
              f"{'Fragmented Tracks (%)':>{col}}  {'Dominant Track Coverage (%)':>{col}}")
    sep = "-" * len(header)

    print()
    print("Table 4: SG track fragmentation relative to AV2 tracks (GT scenario tracks)")
    print(sep)
    print(header)
    print(sep)
    print(f"{n:>{col}}  {frags_mean:>{col}.3f}  {frag_rate:>{col}.1f}  {dom_cov:>{col}.1f}")
    print(sep)
    print()


if __name__ == "__main__":
    main()
