#!/usr/bin/env python3
"""
build_extractions.py — Build extractions.json from SceneFlowLang results.

Reads the per-UUID satisfaction files produced by run_sceneflow_threaded.sh and
writes a compact summary used by the Replication Level 2 table scripts.

Requires:
  replicate_data/matched/track_mappings.json  — generated by generate_track_mappings.py

Run from the repo root:
    python replicate_data/scripts/build_extractions.py
"""

from __future__ import annotations

import json
from pathlib import Path

_REPO_ROOT    = Path(__file__).resolve().parent.parent.parent
MAPPINGS_FILE = _REPO_ROOT / "replicate_data" / "matched" / "track_mappings.json"
RESULTS_BASE  = _REPO_ROOT / "SceneFlowLang" / "my_results"
OUT_FILE      = Path(__file__).resolve().parent.parent / "precomputed" / "extractions.json"

SG_LEVELS = [
    "SG_tracks",
    "SG_tracks_kinematics",
    "SG_tracks_kinematics_map",
]

VARIANTS = [
    "long_following_near_3",
    "long_following_visible_3",
    "long_following_very_near_veh_decel_3.0",
    "cut_in_from_right",
    "cut_in_from_right_snowy",
    "cut_in_from_right_veh_decel",
]


def _load_all_track_mappings() -> dict[str, dict[int, str]]:
    if not MAPPINGS_FILE.exists():
        print(f"ERROR: track_mappings.json not found at {MAPPINGS_FILE}")
        print("       Download track_mappings.json and place it at replicate_data/matched/")
        raise SystemExit(1)
    with open(MAPPINGS_FILE) as f:
        raw = json.load(f)
    # Keys are stored as strings; convert RS2V track IDs back to int for lookup.
    return {uuid8: {int(k): v for k, v in mapping.items()}
            for uuid8, mapping in raw.items()}


def _load_extractions(results_dir: Path, uuid8: str, variant: str,
                      track_mapping: dict[int, str]) -> list[dict]:
    sat_dir = results_dir / uuid8 / variant / "satisfactions"
    if not sat_dir.exists():
        return []
    rows = []
    for jf in sorted(sat_dir.glob("*.json")):
        with open(jf) as f:
            data = json.load(f)
        entity_mapping = data.get("entity_mapping", {})
        track_label = (entity_mapping.get("yield_vehicle_1")
                       or next(iter(entity_mapping.values()), None))
        av2_uuid = None
        if track_label is not None:
            parts = track_label.split("_")
            track_int = int(parts[-1]) if len(parts) >= 3 and parts[0] == "track" else None
            av2_uuid = track_mapping.get(track_int) if track_int is not None else None
        rows.append({
            "av2_track_uuid": av2_uuid,
            "start_s": int(data["start_frame"]) / 1e9,
            "end_s":   int(data["end_frame"])   / 1e9,
        })
    return rows


def build_extractions_summary(all_mappings: dict[str, dict[int, str]]) -> dict:
    summary: dict = {}
    for sg_level in SG_LEVELS:
        results_dir = RESULTS_BASE / sg_level
        if not results_dir.exists():
            print(f"  Skipping {sg_level} (no results found — run replicate_level2.sh first)")
            continue
        print(f"  {sg_level} ...", end=" ", flush=True)
        level_data: dict = {}
        uuid_dirs = sorted(d.name for d in results_dir.iterdir() if d.is_dir())
        for uuid8 in uuid_dirs:
            track_mapping = all_mappings.get(uuid8, {})
            variants_data: dict = {}
            for variant in VARIANTS:
                exts = _load_extractions(results_dir, uuid8, variant, track_mapping)
                if exts:
                    variants_data[variant] = exts
            if variants_data:
                level_data[uuid8] = variants_data
        summary[sg_level] = level_data
        total = sum(len(v) for ld in level_data.values() for v in ld.values())
        print(f"{len(level_data)} logs, {total} extractions")
    return summary


def main() -> None:
    print("Loading track mappings ...")
    all_mappings = _load_all_track_mappings()
    print(f"  {len(all_mappings)} logs loaded")

    print("Building extractions.json ...")
    extractions = build_extractions_summary(all_mappings)
    with open(OUT_FILE, "w") as f:
        json.dump(extractions, f, separators=(",", ":"))
    print(f"  -> {OUT_FILE}\n")
    print("Done. Run the table scripts to verify results match the paper.")


if __name__ == "__main__":
    main()
